# Generated by Django 3.1.7 on 2021-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('venue', models.CharField(max_length=120, verbose_name='Venue')),
                ('manager', models.CharField(max_length=60, verbose_name='Manager')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
